### ISSUE TITLE
Pretrained model checkpoint link has expired

### ISSUE THREAD

**Issue by chelovek21** [seungjunlee96/emergency-triage-of-brain-computed-tomography-via-anomaly-detection-with-a-deep-generative-model#1]
Pretrained model checkpoint link has expired，share it again? thank you

**Comment by seungjunlee96** [comment]
I have updated the expired pretrained model checkpoint link. Here is the updated link for you:

- model checkpoint ([LINK](https://drive.google.com/file/d/1QpzO2f4a8lPgsRpbOMLzkNydf_N3sWnC/view?usp=sharing))
- latent statistics ([LINK](https://drive.google.com/file/d/1MgkCn2ZmciPjfwhN-qQPAIC2p0JS-ULy/view?usp=sharing))

Please let me know if you need any further assistance.
