### ISSUE TITLE
Seeking guidance to run pertained model on custom dataset

### ISSUE THREAD

**Issue by anantpal07** [seungjunlee96/emergency-triage-of-brain-computed-tomography-via-anomaly-detection-with-a-deep-generative-model#3]
We are currently trying to utilise the  pretrained model for the detection of anomalies in CT scans. We have a set of sample CT scan images ready for experimentation. However, we are facing uncertainty regarding the creation of 'bet.npy' files associated with these images.

Could someone kindly provide guidance or instructions on how to generate the 'bet.npy' files for our CT scan dataset? Any assistance or insights would be greatly appreciated.

Thank you in advance for your support.

**Comment by seungjunlee96** [comment]
Hello,

Thank you for reaching out.

To generate 'bet.npy' files, you can use the Brain CT Brain Extraction Tool available at [CT_BET](https://github.com/aqqush/CT_BET) which we used for this study. After using this tool to process your CT scans, you will need to convert the output data from the NIfTI format to the `.npy` format.

If you encounter any issues or have further questions, feel free to ask.

Best regards,

**Comment by anantpal07** [comment]
Hello,

Thank you for your response.

We attempted to utilize the Brain CT Brain Extraction Tool available at [CT_BET](https://github.com/aqqush/CT_BET), as employed in your study. However, we encountered difficulties and were unable to achieve success. Is there an alternative method for generating 'bet.npy' files?

Thank you
