### ISSUE TITLE
Seeking guidance to run pertained model on custom dataset

### ISSUE THREAD

**Issue by anantpal07** [seungjunlee96/emergency-triage-of-brain-computed-tomography-via-anomaly-detection-with-a-deep-generative-model#4]
Hello,

Thank you for your response.

We attempted to utilize the Brain CT Brain Extraction Tool available at [CT_BET](https://github.com/aqqush/CT_BET), as employed in your study. However, we encountered difficulties and were unable to achieve success. Is there an alternative method for generating 'bet.npy' files?

Thank you

**Comment by seungjunlee96** [comment]
Hello,

Thank you for reaching out and using our study. I'm sorry to hear that you're encountering difficulties with the tool,[CT_BET](https://github.com/aqqush/CT_BET).

To assist you better, could you please provide more details about the specific issues you are facing? Information such as error messages, the step at which the process fails, and any other relevant details would be incredibly helpful in diagnosing the problem.

**Comment by anantpal07** [comment]
completed
