### ISSUE TITLE
Gratitude for Your Assistance and CUDA Out of Memory Error

### ISSUE THREAD

**Issue by anantpal07** [seungjunlee96/emergency-triage-of-brain-computed-tomography-via-anomaly-detection-with-a-deep-generative-model#7]
Dear SeungjunLee,

I hope this message finds you well. First and foremost, I want to express my sincere gratitude for your prompt response to my GitHub issue and for taking the initiative to fix the problem by updating the Docker file in the project. Your efforts are highly appreciated, and it's great to see such an active and supportive community around this project.

I am currently trying to run the project on my system, which is equipped with an Nvidia RTX 4070 Ti Super graphics card with 16GB GPU RAM. However, I'm encountering a "CUDA out of memory" error. I understand that my GPU has less memory compared to the 4x Titan RTX 8000 GPUs mentioned in the project documentation.

Given this constraint, I am reaching out to seek your guidance on how to adapt the project to run on my GPU with the available resources. Are there specific parameters or configurations that I can adjust to accommodate the lower GPU memory?

Your expertise and insights would be invaluable in helping me overcome this challenge, and I appreciate any guidance or recommendations you can provide. Thank you once again for your dedication to the project and for your assistance in resolving these issues.

Best regards,

Anant Paliwal
anantpal07

**Comment by seungjunlee96** [comment]
Dear Anant Paliwal,

Thank you for reaching out, and I appreciate your kind words.

In response to the “CUDA out of memory” error you’re encountering, adapting the project for use with an Nvidia RTX 4070 Ti Super, which has 16GB of GPU RAM, presents a significant challenge.

A practical suggestion is to reduce the `batch_size` parameter. This adjustment will enable you to process a limited portion of the CT slices, mitigating the GPU’s memory constraints. However, it’s crucial to acknowledge that such a change may impact the reproducibility of the project’s results as documented, especially under the current hardware limitations.

**Comment by anantpal07** [comment]
Thanks
