### ISSUE TITLE
At what HU levels is the dicom data windowed

### ISSUE THREAD

**Issue by noorfatma** [seungjunlee96/emergency-triage-of-brain-computed-tomography-via-anomaly-detection-with-a-deep-generative-model#9]
Hi,

  First of all a very commendable work done here in the triage. I have some doubts about the input png demo images. As far as I can see, the png is made by combining three grey level dicoms at different HU levels. Can you pls elaborate at what Hu levels are those at. 

Also, it would be helpful if you could elaborate on the preprocessing of dicom data for the custom dataset creation

**Comment by seungjunlee96** [comment]
Hi, 

The method `custom.utils.windowing_brain` ([Link](https://github.com/seungjunlee96/emergency-triage-of-brain-computed-tomography-via-anomaly-detection-with-a-deep-generative-model/blob/3aa8c1b675070411ab88c55c4c755ad6a5cbafb9/custom/utils.py#L51)) involves windowing DICOM images at three specific Hounsfield Unit (HU) levels for brain imaging, aiming to highlight different tissue densities. 

**Three-Channel Processing**: Creates a composite image by adjusting the original DICOM data to three different HU ranges, each assigned to one of the RGB channels:
   - Red Channel: HU values from 5 to 55, emphasizing lower density structures.
   - Green Channel: HU values from 0 to 80, focusing on medium density structures.
   - Blue Channel: HU values from -20 to 180, capturing a broad range of densities.

For custom dataset preparation, images are processed using custom.utils.windowing_brain, resized to 512x512, and then sorted in axial CT slice order using their filename. The processed images are then saved in PNG format for visual assessment and further use.

Furthermore, it requires brain extraction of Brain CT scans using [CT_BET](https://github.com/aqqush/CT_BET). The results of this extraction are saved in NPY format.
